# Welcome to Jekyll!

# -- Site settings -- #
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gautham G
email: gautham.g@live.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a full-stack software engineer passionate about the
  possibilities that exist at the intersection of art,
  engineering, and design. My expertise lies in Javascript,
  AWS, and mobile development. However, I am always excited to
  learn new skills!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  code-citrus

# -- Build settings -- #

# If you are using sass @import statements, you must ensure
# the sass/sass_dir configuration options is set to the base
# directory that contains your scss files to be imported. You
# can also use sass/load_paths for multiple directories.
sass:
  load_paths:
    - _sass
    - node_modules

include:
  - node_modules/

logo: /assets/img/logo.jpg

plugins:
  - jekyll-feed

# 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
